-- =============================================================================
-- Taskmaster Database Schema (Idempotent Migration)
-- Can be safely run multiple times without errors.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Tables
-- ---------------------------------------------------------------------------

-- Profiles (extends Supabase auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  total_points INTEGER DEFAULT 0,
  tasks_completed INTEGER DEFAULT 0,
  consecutive_skips INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tasks (generated by Claude)
CREATE TABLE IF NOT EXISTS public.tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
  submission_type TEXT NOT NULL CHECK (submission_type IN ('image', 'text')),
  max_points INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'skipped')),
  points_awarded INTEGER DEFAULT 0,
  evaluation_feedback TEXT,
  submission_text TEXT,
  submission_image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- ---------------------------------------------------------------------------
-- 2. Views
-- ---------------------------------------------------------------------------

-- Leaderboard view (ranked by total points)
CREATE OR REPLACE VIEW public.leaderboard AS
SELECT
  p.id,
  p.username,
  p.total_points,
  p.tasks_completed,
  RANK() OVER (ORDER BY p.total_points DESC) AS rank
FROM public.profiles p
WHERE p.total_points > 0
ORDER BY p.total_points DESC;

-- ---------------------------------------------------------------------------
-- 3. Indexes
-- ---------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_tasks_user_id ON public.tasks(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON public.tasks(status);
CREATE INDEX IF NOT EXISTS idx_profiles_total_points ON public.profiles(total_points DESC);
CREATE INDEX IF NOT EXISTS idx_tasks_user_status ON public.tasks(user_id, status);

-- Prevent duplicate active tasks per user
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_active_task_per_user
  ON public.tasks(user_id) WHERE status = 'active';

-- ---------------------------------------------------------------------------
-- 4. Row Level Security
-- ---------------------------------------------------------------------------

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- Profiles policies
DROP POLICY IF EXISTS "Users can view all profiles" ON public.profiles;
CREATE POLICY "Users can view all profiles"
  ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
CREATE POLICY "Users can insert own profile"
  ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Tasks policies
-- Remove the dangerously permissive open policy (service role bypasses RLS anyway)
DROP POLICY IF EXISTS "Service role can manage tasks" ON public.tasks;

-- Users can only view their own tasks
DROP POLICY IF EXISTS "Users can view own tasks" ON public.tasks;
CREATE POLICY "Users can view own tasks"
  ON public.tasks FOR SELECT USING (auth.uid() = user_id);

-- No INSERT/UPDATE/DELETE policies needed for authenticated/anon roles:
-- all task mutations go through the backend which uses the service role key
-- (service role bypasses RLS entirely).

-- ---------------------------------------------------------------------------
-- 5. Functions
-- ---------------------------------------------------------------------------

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1))
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop unused legacy functions (not called anywhere, unnecessary attack surface)
DROP FUNCTION IF EXISTS public.update_profile_on_completion(UUID, INTEGER);
DROP FUNCTION IF EXISTS public.update_profile_on_skip(UUID, INTEGER);

-- Atomically complete a task and update the user's profile
CREATE OR REPLACE FUNCTION public.complete_task(
  p_task_id UUID,
  p_user_id UUID,
  p_points INTEGER,
  p_feedback TEXT,
  p_submission_text TEXT DEFAULT NULL,
  p_submission_image_url TEXT DEFAULT NULL
)
RETURNS VOID AS $$
BEGIN
  -- Defense in depth: reject if an authenticated user tries to act as someone else.
  -- Service role calls have auth.uid() = NULL, so they pass through.
  IF auth.uid() IS NOT NULL AND auth.uid() != p_user_id THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  UPDATE public.tasks
  SET status = 'completed',
      points_awarded = p_points,
      evaluation_feedback = p_feedback,
      submission_text = p_submission_text,
      submission_image_url = p_submission_image_url,
      completed_at = NOW()
  WHERE id = p_task_id AND user_id = p_user_id AND status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Active task not found';
  END IF;

  UPDATE public.profiles
  SET total_points = total_points + p_points,
      tasks_completed = tasks_completed + 1,
      consecutive_skips = 0
  WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Atomically skip a task and update the user's profile
CREATE OR REPLACE FUNCTION public.skip_task(
  p_task_id UUID,
  p_user_id UUID,
  p_penalty INTEGER
)
RETURNS VOID AS $$
BEGIN
  -- Defense in depth: reject if an authenticated user tries to act as someone else.
  IF auth.uid() IS NOT NULL AND auth.uid() != p_user_id THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  UPDATE public.tasks
  SET status = 'skipped',
      points_awarded = p_penalty,
      completed_at = NOW()
  WHERE id = p_task_id AND user_id = p_user_id AND status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Active task not found';
  END IF;

  UPDATE public.profiles
  SET total_points = total_points + p_penalty,
      consecutive_skips = consecutive_skips + 1
  WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ---------------------------------------------------------------------------
-- 6. Triggers
-- ---------------------------------------------------------------------------

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ---------------------------------------------------------------------------
-- 7. Storage
-- ---------------------------------------------------------------------------

-- Create the task-images bucket (idempotent)
INSERT INTO storage.buckets (id, name, public)
VALUES ('task-images', 'task-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies: users upload to their own folder (path: {user_id}/...)
DROP POLICY IF EXISTS "Users can upload own task images" ON storage.objects;
CREATE POLICY "Users can upload own task images"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'task-images'
    AND auth.uid() IS NOT NULL
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

DROP POLICY IF EXISTS "Task images are publicly accessible" ON storage.objects;
CREATE POLICY "Task images are publicly accessible"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'task-images');

DROP POLICY IF EXISTS "Users can update own task images" ON storage.objects;
CREATE POLICY "Users can update own task images"
  ON storage.objects FOR UPDATE
  USING (
    bucket_id = 'task-images'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

DROP POLICY IF EXISTS "Users can delete own task images" ON storage.objects;
CREATE POLICY "Users can delete own task images"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'task-images'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

-- ---------------------------------------------------------------------------
-- 8. Grants
-- ---------------------------------------------------------------------------

GRANT SELECT ON public.leaderboard TO authenticated, anon;
