-- Profiles (extends Supabase auth.users)
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  total_points INTEGER DEFAULT 0,
  tasks_completed INTEGER DEFAULT 0,
  consecutive_skips INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tasks (generated by Claude)
CREATE TABLE public.tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('easy', 'medium', 'hard')),
  submission_type TEXT NOT NULL CHECK (submission_type IN ('image', 'text')),
  max_points INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'skipped')),
  points_awarded INTEGER DEFAULT 0,
  evaluation_feedback TEXT,
  submission_text TEXT,
  submission_image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- Leaderboard view
CREATE VIEW public.leaderboard AS
SELECT
  p.id,
  p.username,
  p.total_points,
  p.tasks_completed,
  RANK() OVER (ORDER BY p.total_points DESC) AS rank
FROM public.profiles p
WHERE p.total_points > 0
ORDER BY p.total_points DESC;

-- Indexes
CREATE INDEX idx_tasks_user_id ON public.tasks(user_id);
CREATE INDEX idx_tasks_status ON public.tasks(status);
CREATE INDEX idx_profiles_total_points ON public.profiles(total_points DESC);

-- Composite index for the frequent (user_id, status) lookup
CREATE INDEX idx_tasks_user_status ON public.tasks(user_id, status);

-- Prevent duplicate active tasks per user
CREATE UNIQUE INDEX idx_one_active_task_per_user ON public.tasks(user_id) WHERE status = 'active';

-- RLS Policies
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view all profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can view own tasks" ON public.tasks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Service role can manage tasks" ON public.tasks FOR ALL USING (true);

-- Function to create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- RPC: Update profile on task completion (kept for backward compatibility)
CREATE OR REPLACE FUNCTION public.update_profile_on_completion(p_user_id UUID, p_points INTEGER)
RETURNS VOID AS $$
BEGIN
  UPDATE public.profiles
  SET total_points = total_points + p_points,
      tasks_completed = tasks_completed + 1,
      consecutive_skips = 0
  WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC: Update profile on task skip (kept for backward compatibility)
CREATE OR REPLACE FUNCTION public.update_profile_on_skip(p_user_id UUID, p_penalty INTEGER)
RETURNS VOID AS $$
BEGIN
  UPDATE public.profiles
  SET total_points = total_points + p_penalty,
      consecutive_skips = consecutive_skips + 1
  WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC: Atomically complete a task and update profile in one transaction
CREATE OR REPLACE FUNCTION public.complete_task(
  p_task_id UUID,
  p_user_id UUID,
  p_points INTEGER,
  p_feedback TEXT,
  p_submission_text TEXT DEFAULT NULL,
  p_submission_image_url TEXT DEFAULT NULL
)
RETURNS VOID AS $$
BEGIN
  UPDATE public.tasks
  SET status = 'completed',
      points_awarded = p_points,
      evaluation_feedback = p_feedback,
      submission_text = p_submission_text,
      submission_image_url = p_submission_image_url,
      completed_at = NOW()
  WHERE id = p_task_id AND user_id = p_user_id AND status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Active task not found';
  END IF;

  UPDATE public.profiles
  SET total_points = total_points + p_points,
      tasks_completed = tasks_completed + 1,
      consecutive_skips = 0
  WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- RPC: Atomically skip a task and update profile in one transaction
CREATE OR REPLACE FUNCTION public.skip_task(
  p_task_id UUID,
  p_user_id UUID,
  p_penalty INTEGER
)
RETURNS VOID AS $$
BEGIN
  UPDATE public.tasks
  SET status = 'skipped',
      points_awarded = p_penalty,
      completed_at = NOW()
  WHERE id = p_task_id AND user_id = p_user_id AND status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Active task not found';
  END IF;

  UPDATE public.profiles
  SET total_points = total_points + p_penalty,
      consecutive_skips = consecutive_skips + 1
  WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Storage bucket for task images (run via Supabase dashboard)
-- INSERT INTO storage.buckets (id, name, public) VALUES ('task-images', 'task-images', true);
